#!/bin/bash

cd p1
ocamlc -o nombre nombre.ml
ocamlc -c expr1.ml
ocamlc -c expr2.mli expr2.ml
rm nombre
cd ..

cd p2
ocamlc -o pi pi.ml
ocamlc -o e e.ml
ocamlc -o fact fact.ml
rm pi e fact
cd ..

cd p3
ocamlc -c ej31.mli ej31.ml
ocamlc -c condis.ml
ocamlc -c ej33.mli ej33.ml
ocamlc -o fib fib.ml
ocamlc -c prime.mli prime.ml
rm fib
cd ..

cd p4
ocamlc -c ej41.mli ej41.ml
ocamlc -c power.mli power.ml
ocamlc -c mcd.mli mcd.ml
cd ..

cd p5
ocamlc -c collatz.mli collatz.ml
cd ..

cd p6
ocamlc -c powmod.mli powmod.ml
ocamlc -c ej62.mli ej62.ml
cd ..
