#!/bin/bash

echo "#################################################"
echo "CAT QUEENS.ML"
echo ""
echo ""
cat queens.ml
echo ""
echo ""

echo "#################################################"
echo "LIMPIAMOS Y RECOMPILAMOS TODO"
echo ""
echo ""
make clean
make
echo ""
echo ""
echo "#################################################"

echo "INICIO DE LOS TESTS"
echo ""
echo ""
./test 0
./test 1
./test 2
./test 3
./test 4
./test 5
./test 6
./test 7
./test 8
./test 9
./test 10
./test 11
./test 12
./test 13
./test 14
./test 15
